name: "🐛 Bug Report"
description: Report a bug in the Seshat API Python package.
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter the code you ran that caused the bug.
  - type: textarea
    id: logs
    attributes:
      label: "Error message"
      description: Please copy and paste the error message. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      description:
        Please confirm the following are completed before this issue can be closed.
      options:
        - label: A fix for the bug has been developed on a branch.
        - label: A pull request has been created for the new branch to be merged into the main branch.